Intro kath
danimarinaaa/grupal2018 pull request #1
Opened 2019-06-01 23:49 UTC by kathporras16

Esta es mi rama desde la cual estaré trabajando la intro

2019-06-02 22:54 UTC, danimarinaaa commented
Perfecto Kathe voy a revisar, muchas gracias

2019-06-02 23:10 UTC, danimarinaaa requested changes

2019-06-02 23:10 UTC, danimarinaaa commented on Informe/informe2019.Rmd
> +  Los individuos de esta especie han sido extraídos por las personas que habitan cerca de las costas, ya sea manualmente o por buceo a pulmón, con el fin de consumirlo. La especie se ha visto afectad
Kathe super bien me parece importante ir ordenando la introduccion de cacuerdo a como acordamos:

1.Ecosistemas rocosos
Ubicación
Dinámica mareas
Diversidad
2.Strombus galeatus
Distribución
Taxonomía
Ecología
Ciclo de vida
Explotación del Cambute
3.Dinámica de poblaciones
Modelos de crecimiento y extinción
Objetivo de esta investigación

2019-06-02 23:11 UTC, danimarinaaa commented on Informe/informe2019.Rmd
> +  Los individuos de esta especie han sido extraídos por las personas que habitan cerca de las costas, ya sea manualmente o por buceo a pulmón, con el fin de consumirlo. La especie se ha visto afectad
Como intentar integrar la intro anterior y esta.

2019-06-02 23:17 UTC, danimarinaaa approved these changes

2019-06-02 23:17 UTC, danimarinaaa commented on Informe/informe2019.Rmd
> +  Los individuos de esta especie han sido extraídos por las personas que habitan cerca de las costas, ya sea manualmente o por buceo a pulmón, con el fin de consumirlo. La especie se ha visto afectad
Lo aprobe para acomodarlo Kath

2019-06-03 03:38 UTC, kathporras16 commented
Ok, excelente. Trabajaré en ello. Gracias!

2019-06-03 07:05 UTC, merged